### ISSUE TITLE
tests failing for stackage nightly (GHC-9.2.2)

### ISSUE THREAD

**Issue by cdornan** [turboMaCk/aeson-combinators#31] opened 2022-05-03 16:23 UTC
We are seeing:
```
Test suite failure for package aeson-combinators-0.1.0.0
    spec:  executable not found
```
It is still in the build but has been marked as expecting tests failures.

**Comment by turboMaCk** [comment] 2022-05-03 18:54
I don't know how I can reproduce the problem. `spec` is the [tests binary itself](https://github.com/turboMaCk/aeson-combinators/blob/d6849c7a0e61b6a95bcf1775043a85f83b252ef3/aeson-combinators.cabal#L70).

This is what I did to reproduce build with aeson 2 https://github.com/turboMaCk/aeson-combinators/pull/29/files.

I'm able to run tests using stack successfully locally as well as in CI. GHC version being used is:

```
$ stack ghc -- --version
Stack has not been tested with GHC versions above 9.0, and using 9.2.2, this may fail
Stack has not been tested with Cabal versions above 3.4, but version 3.6.3.0 was found, this may fail
The Glorious Glasgow Haskell Compilation System, version 9.2.2
```

```
$ stack exec ghc-pkg list | grep aeson
Stack has not been tested with GHC versions above 9.0, and using 9.2.2, this may fail
Stack has not been tested with Cabal versions above 3.4, but version 3.6.3.0 was found, this may fail
    aeson-2.0.3.0
/home/marek/Projects/aeson-combinators/.stack-work/install/x86_64-linux-nix/a5a8c67917710377c410f7fbafb0c088649ee8cb3f2f87057de1134b9be592e7/9.2.2/pkgdb
    aeson-combinators-0.1.0.0
 ```

**Comment by turboMaCk** [comment] 2022-05-03 20:07
I think i might have found the issue in https://github.com/turboMaCk/aeson-combinators/pull/32 it seems that benchmarks were not compiling with ghc 9.2.2 because of change in -XTypeApplications. changing `@ Foo` to `@Foo` fixed the problem it seems. In CI benchmarks run only for nix based builds not for stack job so that might have been the cause of failure for stackage.

**Comment by turboMaCk** [comment] 2022-05-03 20:13
I believe 0.1.0.1 release should resolve the issue (by fixing benchmark). Could you please confirm that @cdornan ? I'm closing the issue but feel free to reopen it in case I'm mistaken.

**Comment by turboMaCk** [comment] 2023-12-28 10:00
I believe this issue was resolved back in May 2022. closing

**Closed as completed by turboMaCk** 2023-12-28 10:00 UTC
